import Head from "next/head";
import React from "react";

interface ContainerParams {
  children: any;
}

const Container: React.FC<ContainerParams> = ({ children }) => {
  return (
    <div className=" h-full absolute w-full bg-gradient-to-b from-white via-white to-cyan-400/40 pl-6 pt-6 pr-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>{children}</main>
    </div>
  );
};

export { Container };
